version: '2.13.0'
services: 
  app:
    container_name: ecommerce
    image: ecommerce
    build: ./
    ports:
      - "8080:8080"
    depends_on: 
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgresqldb:
    container_name: ecommercedb
    image: postgres:alpine
    ports:
      - "5432-5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce